export const OCPP_SUPPORTED_VERSIONS_META = 'OCPP_SUPPORTED_VERSIONS';
export const OCPP_DEBUGGER_TOKEN = 'OCPP_DEBUGGER_TOKEN';
export const OCPP_VERSIONS_TOKEN = 'OCPP_VERSIONS';
export const OCPP_SOCKET_PORT_TOKEN = 'OCPP_SOCKET_PORT';
export const OCPP_TLS_OPTIONS_TOKEN = 'OCPP_TLS_OPTIONS';
export const OCPP_LOGGER_TOKEN = 'OcppModule';

export const OCPP_CONTROLLER_META = 'OCPP_CONTROLLER_META';
export const OCPP_MESSAGE_META = 'OCPP_MESSAGE_META';
